version: '3.9'
services:
  web:
    build:
      context: .
      dockerfile: docker/prod.Dockerfile
    env_file:
      - .env.prod
    depends_on:
      - db
    command: gunicorn backend.wsgi:application --bind 0.0.0.0:8000
    restart: always

  db:
    image: postgres:14
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: surfix
      POSTGRES_USER: surfix_user
      POSTGRES_PASSWORD: surfix_pass

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - static_volume:/app/static
    depends_on:
      - web

volumes:
  postgres_data:
  static_volume:
