version: '3.9'
services:
  web:
    build:
      context: .
      dockerfile: docker/prod.Dockerfile
    env_file:
      - .env.prod
    depends_on:
      - db
    command: sh /app/entrypoint.sh
    volumes:
      - static_volume:/app/static
    networks:
      - default
      - reverse-proxy

  db:
    image: postgres:14
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env.prod


volumes:
  postgres_data:
  static_volume:

networks:
  reverse-proxy:
    external: true
    name: reverse-proxy_default
