# Generated by Django 4.2.23 on 2025-06-16 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, max_length=100, null=True)),
                ('grano', models.CharField(blank=True, max_length=100, null=True)),
                ('precio_unidad', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('formato', models.CharField(blank=True, max_length=100, null=True)),
                ('descuento', models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True)),
                ('ad', models.CharField(blank=True, max_length=100, null=True)),
                ('largo', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('ancho', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('litros', models.DecimalField(blank=True, decimal_places=0, max_digits=2, null=True)),
                ('producto', models.CharField(blank=True, max_length=100, null=True)),
                ('medidas', models.CharField(blank=True, max_length=100, null=True)),
                ('unidades_x_caja', models.IntegerField(blank=True, null=True)),
                ('categoria', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
