# Generated by Django 4.2.13 on 2024-07-23 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=100)),
                ('grano', models.CharField(blank=True, max_length=50, null=True)),
                ('precio_unidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('formato', models.CharField(blank=True, max_length=100, null=True)),
                ('descuento', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('ad', models.CharField(blank=True, max_length=100, null=True)),
                ('ancho', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('largo', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('rollos', models.IntegerField(blank=True, null=True)),
                ('litros', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
            ],
        ),
    ]
