# Generated by Django 4.2.13 on 2024-07-23 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='precio_unidad',
        ),
        migrations.AddField(
            model_name='producto',
            name='precio',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='ancho',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='descuento',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='grano',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='largo',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='litros',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='rollos',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
