# Generated by Django 4.2.13 on 2024-07-24 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listas', '0003_producto_medidas_producto_producto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='precio',
            field=models.FloatField(default=0.0),
        ),
    ]
