# Generated by Django 4.2.13 on 2024-07-24 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listas', '0004_alter_producto_precio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='medidas',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='producto',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='unidades_x_caja',
        ),
        migrations.AlterField(
            model_name='producto',
            name='ad',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='codigo',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='producto',
            name='descuento',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='grano',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
