# Generated by Django 4.2.13 on 2024-07-24 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listas', '0006_producto_medidas_producto_producto_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Abrasivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=100, unique=True)),
                ('producto', models.CharField(blank=True, max_length=255, null=True)),
                ('medidas', models.CharField(blank=True, max_length=255, null=True)),
                ('unidades_x_caja', models.IntegerField(blank=True, null=True)),
                ('precio', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('dto', models.CharField(blank=True, max_length=50, null=True)),
                ('ad', models.CharField(blank=True, max_length=50, null=True)),
                ('grano', models.CharField(blank=True, max_length=50, null=True)),
                ('formato', models.CharField(blank=True, max_length=255, null=True)),
                ('descuento', models.CharField(blank=True, max_length=50, null=True)),
                ('ancho', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('largo', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('rollos', models.IntegerField(blank=True, null=True)),
                ('litros', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Producto',
        ),
    ]
