# Generated by Django 4.2.13 on 2024-07-24 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listas', '0007_abrasivo_delete_producto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abrasivo',
            name='ad',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='abrasivo',
            name='descuento',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='abrasivo',
            name='dto',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='abrasivo',
            name='formato',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='abrasivo',
            name='grano',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='abrasivo',
            name='medidas',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
