# Generated by Django 4.2.13 on 2024-07-24 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listas', '0008_alter_abrasivo_ad_alter_abrasivo_descuento_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='abrasivo',
            name='dto',
        ),
        migrations.AlterField(
            model_name='abrasivo',
            name='codigo',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='abrasivo',
            name='producto',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
