# Generated by Django 4.2.13 on 2024-07-24 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listas', '0009_remove_abrasivo_dto_alter_abrasivo_codigo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cintas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Rollos', models.CharField(max_length=100)),
            ],
        ),
    ]
