# Generated by Django 4.2.13 on 2024-07-24 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listas', '0010_cintas'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cintas',
            old_name='Rollos',
            new_name='rollos',
        ),
    ]
