# Generated by Django 4.2.13 on 2024-07-24 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listas', '0011_rename_rollos_cintas_rollos'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cintas',
            new_name='Cinta',
        ),
    ]
