# Generated by Django 4.2.13 on 2024-07-24 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listas', '0012_rename_cintas_cinta'),
    ]

    operations = [
        migrations.AddField(
            model_name='cinta',
            name='ad',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cinta',
            name='ancho',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='cinta',
            name='codigo',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cinta',
            name='descuento',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cinta',
            name='formato',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cinta',
            name='grano',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cinta',
            name='largo',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='cinta',
            name='litros',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='cinta',
            name='medidas',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cinta',
            name='precio',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='cinta',
            name='producto',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cinta',
            name='unidades_x_caja',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cinta',
            name='rollos',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
