# Generated by Django 4.2.13 on 2024-07-24 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listas', '0013_cinta_ad_cinta_ancho_cinta_codigo_cinta_descuento_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=255)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
                ('precio_unidad', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('formato', models.CharField(blank=True, max_length=255, null=True)),
                ('descuento', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('ad', models.CharField(blank=True, max_length=255, null=True)),
                ('largo', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('ancho', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('litros', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('producto', models.CharField(blank=True, max_length=255, null=True)),
                ('medidas', models.CharField(blank=True, max_length=255, null=True)),
                ('unidades_x_caja', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Cinta',
        ),
        migrations.RenameField(
            model_name='abrasivo',
            old_name='ancho',
            new_name='precio_unidad',
        ),
        migrations.RemoveField(
            model_name='abrasivo',
            name='largo',
        ),
        migrations.RemoveField(
            model_name='abrasivo',
            name='litros',
        ),
        migrations.RemoveField(
            model_name='abrasivo',
            name='medidas',
        ),
        migrations.RemoveField(
            model_name='abrasivo',
            name='precio',
        ),
        migrations.RemoveField(
            model_name='abrasivo',
            name='producto',
        ),
        migrations.RemoveField(
            model_name='abrasivo',
            name='rollos',
        ),
        migrations.RemoveField(
            model_name='abrasivo',
            name='unidades_x_caja',
        ),
        migrations.AlterField(
            model_name='abrasivo',
            name='ad',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='abrasivo',
            name='codigo',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='abrasivo',
            name='descuento',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='abrasivo',
            name='formato',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='abrasivo',
            name='grano',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
