# Generated by Django 4.2.13 on 2024-07-28 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listas', '0015_delete_producto_abrasivo_ancho_abrasivo_largo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='abrasivo',
            name='categoria',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
