# Generated by Django 4.2.13 on 2024-07-28 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listas', '0016_abrasivo_categoria'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Abrasivo',
            new_name='Producto',
        ),
    ]
