# Generated by Django 4.2.13 on 2024-08-07 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listas', '0017_rename_abrasivo_producto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('direccion', models.CharField(max_length=255)),
                ('website', models.URLField(blank=True, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('redes_sociales', models.TextField(blank=True, null=True)),
                ('consulta', models.CharField(max_length=255)),
                ('mapa_url', models.URLField()),
            ],
        ),
    ]
