# Generated by Django 4.2.13 on 2024-08-08 02:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listas', '0018_cliente'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cliente',
        ),
    ]
