# Generated by Django 4.2.15 on 2025-01-14 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listas', '0020_alter_producto_ancho_alter_producto_descuento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='litros',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=2, null=True),
        ),
    ]
